# Generated by Django 4.0.6 on 2022-07-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='laptops',
            name='memory',
            field=models.IntegerField(default=8),
        ),
    ]
